### ISSUE TITLE
OSGeo4W install

### ISSUE THREAD

**Issue by elil** [eachiaradia/IOGeopaparazzi#2]
This may or may not be related to #1, I tried an install on OSGeo4W with 2.18.3 and ran into `Wrong value for parameter "Msys folder":` errors.  

Looking around the internet, those might have been related to other providers and I was eventually able to make an empty msys folder where expected and get it turned on as a provider.  

Once running the gpap to vector layers tool, it ends in an error `KeyError: u'map'`.  It partially creates the notes, image notes, and tracklogs.  This error could result from an improper install as noted above.  It could also be a corrupted .gpap file.  [Stage](https://github.com/moovida/STAGE/releases) also throws an error on this .gpap file although it seems to successfully continue and export the data.

**Comment by elil** [comment]
I found some other .gpap files to test.  The gpap to vector layers tool ran correctly with no errors and apparently correct output.  

So the first .gpap file I tried appears to be partially corrupted.  

OSGeo4W with both 2.14.? and 2.18.3 ran into `Wrong value for parameter "Msys folder": errors.`  Creating that empty folder at the requested location allowed the install to continue and apparently work correctly.

**Comment by eachiaradia** [comment]
Hi Eli,
I test a fresh installation of QGIS 2.18.4 with the WIN installer and, whitout the plugin installed I obtained the error related to "Msys folder" as you reported. I think it is something related to the installation chain of QGIS and processing in particular.
I'm glad to read that the plugin works OK in most of your case.
About the keyError that you reported, it is actually a bug as the "map" item is not supported in the current release. I will include it in the next release as soon as possible as I want to include also some other fixings in order to not overload the plugin repository with too much close release.

**Comment by eachiaradia** [comment]
I think I resolved also the "map" error so make a test with your corrupted .gpap if you want. Current version is number 0.1.3. Please wait for approval or download it from github.
Thanks
enrico

**Comment by elil** [comment]
Thanks!  

I upgraded the plugin to 0.1.3 and tested it again.  This time it appeared to work correctly also exporting "map" notes.

**Comment by eachiaradia** [comment]
Perfect! I think this issue could be closed.
